# Generated by Django 4.0.4 on 2022-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('second_name', models.CharField(db_index=True, max_length=50)),
                ('age', models.SmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateField(auto_now=True)),
                ('is_agree', models.BooleanField(default=False)),
            ],
        ),
    ]
